//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Comment
    {
        public int id { get; set; }
        public int Hotelid { get; set; }
        public string text { get; set; }
        public string author { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
